use_frameworks!

target 'AdaptiveSkeletonClimbing_Example' do
  pod 'AdaptiveSkeletonClimbing', :path => '../'

  target 'AdaptiveSkeletonClimbing_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
